---
deployment:
  tasks:
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan down --retry=10
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan config:cache
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan route:cache
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan view:cache
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan migrate --force
    - /usr/local/bin/php /home/twmaorgn/public_html/twcaglobal.org/artisan up
